### ISSUE TITLE
Possible to run with singularity but without docker?

### ISSUE THREAD

**Issue by samlipworth** [francesccoll/powerbacgwas#1]
The installation instructions say you need docker or singulatiry - I have singularity and nextflow and running the help flag works but then when I run the script it complains that I don't have docker (which I don't because our cluster admin team won't let us) - is it possible to run powerbacgwas with singularity but without docker?

thanks.  

`Error executing process > 'PREPARE_PG:roary_to_plink_files (1)'

Caused by:
  Process `PREPARE_PG:roary_to_plink_files (1)` terminated with an error exit status (127)

Command executed:

  roary_to_plink_files.py --gene_presence_absence "gene_presence_absence.Rtab" --input_format 2 --output_prefix "out"

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.run: line 68: docker: command not found

Work dir:
  /mnt/data/analysis/sam/powerbacgwas/nextflow/work/8a/d0dc7e6d17a12899aeefa321b1a319
`

**Comment by francesccoll** [comment]
By default docker is used. You can use singularity without docker using the option "-profile farm" when executing your nextflow command, e.g.:
`nextflow run main.nf --outprefix efm_clade.pg --run_prepare_pangenome --pangenome efm_clade.gene_presence_absence.Rtab --num_cores 8 -profile farm`

The first time you run this option will be get the following message:
> Pulling Singularity image docker://francesccoll/powerbacgwas:amd64 [cache /nfs/users/nfs_f/fc4/lustre_scratch118/49.gwas_power_calculations/nextflow/francesccoll-powerbacgwas-amd64.img]

After which the singularity image (francesccoll-powerbacgwas-amd64.img) will be stored in your working directory.

If you want to submit a nextflow command as a job on your cluster you can use the option "-profile farm,lsf", e.g.:
`nextflow run main.nf --outprefix efm_clade.pg --run_prepare_pangenome --pangenome efm_clade.gene_presence_absence.Rtab --num_cores 8 -profile farm,lsf`

You may need to edit the configuration file (nextflow.config) to create a new profile matching your system’s cluster configuration.

**Comment by samlipworth** [comment]
Great thanks very much.
